# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fd114590f7b1dc063f5b6351d7e565171055369e031adfa807fd67f487f9c1e56b54edffde0ad85c07d14aa33cd33e527c0953d4914953d7e39c5750803a0e5

test:
  secret_key_base: f5b92d6fa65342194f59c4ed7897b9fc5e54580bbe869d167d5b9c96bf045d0de2b11765e4df67d45a7642dfe02813ed11ddece91978e2395289645bf5febcd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
